### ISSUE TITLE
Potencijalna unapredjenja

### ISSUE THREAD

**Issue by ivan-ristovic** [matf-pp2019/KriLa#1]
- Mozda zakljuciti unos na desni klik? A ako je vec zakljucen unos, da desni klik brise platno? 
- Refleksija se uvek radi u odnosu na X osu? Ako da, onda je parametar teta nepotreban (ako se postavi teta na neku vrednost transformacija se ne izvrsava kako treba)

**Comment by matfija** [comment]
- Prihvaćena je prva sugestija, pa i proširena postavljanjem srednjeg dugmeta kao novog načina za nalazak konveksnog omotača; stvarno je olakšan rad kad nije obavezna upotreba menija.
- Usput su dorađene još neke stvari koje smo primetili između predaje i novih izmena: upotreba BooleanVar umesto IntVar, te direktna upotreba tih vrednosti (bez pomoćnih promenljivih), zatim je onemogućeno nepravilno inverzno smicanje, popravljen algoritam za omot, izbrisane suvišne linije koda i malčice proširena geometrijska biblioteka. Možda bude još takvih sitnih izmena do utorka.
- Na pitanje u vezi sa refleksijom biće uskoro konkretno odgovoreno dodavanjem nove stavke u meniju (npr. "Pomoć") koja će lepo opisati šta koji parametar predstavlja. Komentar zasad: refleksija se u suštini vrši u odnosu na pravu. Koristimo homogenu matricu oblika:

     <a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;\cos(2\theta)&space;&&space;\sin(2\theta)&space;&&space;0&space;\\&space;\sin(2\theta)&space;&&space;-\cos(2\theta)&space;&&space;0&space;\\&space;0&space;&&space;0&space;&&space;1&space;\end{bmatrix}" target="_blank"><img src="https://latex.codecogs.com/svg.latex?\begin{bmatrix}&space;\cos(2\theta)&space;&&space;\sin(2\theta)&space;&&space;0&space;\\&space;\sin(2\theta)&space;&&space;-\cos(2\theta)&space;&&space;0&space;\\&space;0&space;&&space;0&space;&&space;1&space;\end{bmatrix}" title="\begin{bmatrix} \cos(2\theta) & \sin(2\theta) & 0 \\ \sin(2\theta) & -\cos(2\theta) & 0 \\ 0 & 0 & 1 \end{bmatrix}" /></a>

- Njeno tumačenje je sledeće: reflektuj tačku u odnosu na pravu koja sa x osom zaklapa ugao θ. Dakle, ukoliko korisnik želi refleksiju u odnosu na pravu y = 0 (znači, x osu), zadaće ugao 0 (ili 180, 360 itd.). Ukoliko želi u odnosu na npr. x = 5, zadaće ugao 90 (ili 270 itd.) ali i tačku te prave kojom će centrirati transformaciju baš oko nje, kao što je (5, 0), (5, -10) ili možda (5, 97). Sveukupno, puno značenje refleksije u konktekstu GeoDemonstrator-a (ideja je izvorno sa časova Geometrije) jeste sledeće: reflektuj tačku u odnosu na pravu koja sa x osom zaklapa ugao θ, a koja prolazi kroz tačku (t1, t2).
